### ISSUE TITLE
Extending an experiment

### ISSUE THREAD

**Issue by llrs** [llrs/experDesign#22]
Sometimes people sequence 50 samples and then wants to add 25 more samples to that cohort. 
Explain some problems on the vignette.
Provide a specific function.
 - Check which are old and which new
 - Check if any variable matches that (warn, that results will be confounded) (perhaps check that in the normal functions too)
 - Suggest which old samples to add to avoid batch effects.

**Comment by llrs** [comment]
This other package can be relevant: https://github.com/hoehleatsu/socialroulette/

**Comment by dwuab** [comment]
I'm also interested in this issue too. However, I don't understand how the package socialroulette could be revlevant.

**Comment by llrs** [comment]
Hi Wu, thanks for commenting showing your interest! Given that someone else is interested I might dedicate some time to provide a solution to this.
Probably extending experiment is not accurate ( I am not native speaker, so there might be better expressions for it) but I haven't come up with or found a better name for it. 

On the [CRAN task View of Experimental Design](https://cran.r-project.org/web/views/ExperimentalDesign.html) there might be something, perhaps adaptive design is better, or we might something relevant on the references provided.

**Comment by llrs** [comment]
It might be interesting to use Minirand for this (check [this thread in twitter](https://twitter.com/jkdempc/status/1615008875056435201)), instead of provide my own solution.

**Comment by llrs** [comment]
Hi @dwuab, I've added some functions in the devel version (soon to be released). There are a `follow_up` and `follow_up2` functions to help with this.

I am still unsure about the name, let me know if these functions help you.
Note that I also added a new function `check_data` to provide some feedback about the data. 

What I  haven't added yet is suggesting some samples to avoid a batch effect.
