### ISSUE TITLE
`spatial()` assigns multiple samples to the same plate position in the same batch

### ISSUE THREAD

**Issue by AnnaPagotto** [llrs/experDesign#45]
Hi Lluís, thank you for this amazing package. I'm using it for my project, but I encountered some issues when distributing the samples in the plate grid. I have some cases where `spatial()` assigns the same position in the same batch to two samples.
Could you help me with that?

Thank you a lot!
Best,
Anna

**Comment by llrs** [comment]
Hi Anna, happy to hear from a happy user.
 
Sorry to hear that `spatial` doesn't fully work. I think I tested to prevent this from happening, but I will give it a look. Could you provide the code where this happens? This way I will make sure it won't happen again.

**Comment by AnnaPagotto** [comment]
Hi Lluis,

Thank you very much for the super fast reply.
Here is the code and the dataset.
Thanks!

Anna

Il giorno mar 5 dic 2023 alle ore 12:15 Lluís Revilla <
***@***.***> ha scritto:

**Comment by AnnaPagotto** [comment]
Oh, sorry, I didn't realise it.
Let me know if I can provide with anything else. I can still send you the code if you wish.

**Comment by AnnaPagotto** [comment]
Hi Lluis,

I'm assigning the position to my controls separately, hence this should be
enough for now.

Thank you a lot for your work!

**Comment by AnnaPagotto** [comment]
Hi Lluis, 
I removed and reinstalled the package. I thought that was sufficient to have the fixed version, but the bug is still there. What do you mean by "fixed locally"? Sorry for my ignorance.
Anna

**Comment by llrs** [comment]
I meant that it was only in my computer, not yet on github or CRAN.
 
To install the package with the fix you will need to use `remotes::install_github("llrs/experDesign")` and it will install the development version with the fix. You don't need to uninstall it and reinstall it again, but you will need to close R and start again R after the installation to be sure that the new version is used.

If it is not fixed then I would need to know the code used and the experDesign version used.

**Comment by AnnaPagotto** [comment]
Sorry, it was a typo, I have age as numeric indeed. 
PS: yes I blocked the first and the last two columns. And I used ggplate for the plot :)

**Comment by AnnaPagotto** [comment]
It is perfectly working now! Thank you a lot!

**Comment by llrs** [comment]
Glad it works now! I hope it helps well designing your experiment!
Thanks for the tip about ggplate! I might use it in the future.
